name: Vote once

on:
  fork:
  push:
  workflow_dispatch:
  #schedule:
  #  - cron:  '*/5 * * * *' # every 5 minutes ist the smallest possible number -> not viable
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: IP
      run: ifconfig
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run once
      run: python3 main.py
    
    #- name: Write to text file
    #  run: echo "Zensurensohn" >> votes.txt
    
    #- name: Commit files
    #  run: |
    #    git config --local user.email "vote@bot.de"
    #    git config --local user.name "Vote Bot"
    #    git add -A
    #    git commit -m "triggering next vote" -a
    
    #- name: Push changes
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    branch: master#
    
    - name: Trigger next vote
      run: |
        echo $GITHUB_REPOSITORY
        curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
        --data '{"event_type": "vote"}'
